name: Update YouTube M3U Playlist

on:
  schedule:
    - cron: '*/1 * * * *'  # Menjalankan setiap 1 menit
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install yt-dlp
        run: pip install yt-dlp

      - name: Run script
        run: python get-m3u8.py

      - name: Commit if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add playlist.txt
          git diff --quiet && git diff --staged --quiet || git commit -m "Update playlist.txt"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Anang110400/kartanagari-tv.git
          git push
